"""Narratives -- the first pillar and the product's centre of gravity.

Two rules enforced here rather than in the UI:

* ``PATCH`` sets ``edited_by_user``, and a reclustering run must never overwrite
  an edited title. The enforcement lives in ``app/tasks/nlp.py`` and there is a
  test for it, but the flag is set here.
* ``/score`` never returns a bare number. It returns the score, the three
  components, the weights that were applied, whether they were renormalized, and
  the formula version. A number the UI cannot explain in one click is a failed
  requirement.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Query, Response, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.db import get_session
from app.deps import Filters, Pagination, RequireRead, RequireWrite, rate_limit
from app.errors import NotFound
from app.mock import responses as mock
from app.schemas.actors import AuthorOut
from app.schemas.common import JobAccepted, PageResponse
from app.schemas.compass import (
    CompassContext,
    CompassFeedback,
    CompassFeedbackResult,
)
from app.schemas.narratives import (
    NarrativeCohortShare,
    NarrativeCreate,
    NarrativeDetail,
    NarrativeFreshness,
    NarrativeScoreExplanation,
    NarrativeSummary,
    NarrativeTimeline,
    NarrativeUpdate,
)
from app.schemas.posts import PostOut

router = APIRouter(prefix="/narratives", tags=["narratives"], dependencies=[Depends(rate_limit)])
compass_router = APIRouter(prefix="/compass", tags=["compass"], dependencies=[Depends(rate_limit)])


def _demo_narrative(narrative_id: str):
    narrative = mock.corpus().by_narrative.get(narrative_id)
    if narrative is None:
        raise NotFound(f"No narrative with id {narrative_id}.", code="narrative_not_found")
    return narrative


# ---------------------------------------------------------------------------
# feed and detail
# ---------------------------------------------------------------------------
@router.get(
    "",
    response_model=PageResponse[NarrativeSummary],
    summary="The narrative feed",
    description=(
        "Each item carries the full six-field scorecard and the AI-generation metadata "
        "the UI's `✨ Generated by AI` pill is rendered from."
    ),
)
async def list_narratives(
    principal: RequireRead,
    filters: Filters,
    page: Pagination,
    session: Annotated[AsyncSession, Depends(get_session)],
    sort: Annotated[str, Query(pattern="^(priority|date|engagement|posts)$")] = "priority",
    q: str | None = None,
) -> PageResponse[NarrativeSummary]:
    if mock.demo_mode():
        return mock.narratives_page(filters, page, sort, q)
    from app.repositories.narratives import list_narratives as query_narratives

    return await query_narratives(session, filters, page, sort=sort, q=q)


@router.post(
    "",
    response_model=NarrativeDetail,
    status_code=status.HTTP_201_CREATED,
    summary="Create a manual narrative",
    description=(
        "A hand-built narrative from the Compose/Curate page. `is_manual` is set, and "
        "reclustering leaves it alone entirely."
    ),
)
async def create_narrative(
    body: NarrativeCreate,
    principal: RequireWrite,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> NarrativeDetail:
    if mock.demo_mode():
        return mock.to_narrative_detail(mock.corpus().narratives[7])
    from app.repositories.narratives import create_manual_narrative

    return await create_manual_narrative(session, body)


@router.get("/freshness", response_model=NarrativeFreshness, summary="Clustering freshness")
async def freshness(
    principal: RequireRead,
    project_id: str,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> NarrativeFreshness:
    """Backs the 'Generated X ago / Update Now' pattern.

    Declared before ``/{narrative_id}`` on purpose: FastAPI matches routes in
    declaration order, and a literal path segment registered after a parameter
    of the same shape is unreachable.
    """
    if mock.demo_mode():
        return mock.narrative_freshness()
    from app.repositories.narratives import clustering_freshness

    return await clustering_freshness(session, project_id)


@router.post(
    "/recluster",
    response_model=JobAccepted,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Recluster the project",
    description=(
        "Returns immediately with a job id. Titles and summaries an analyst has edited "
        "are preserved across the run; manual narratives are not touched at all."
    ),
)
async def recluster(
    principal: RequireWrite,
    project_id: str,
    session: Annotated[AsyncSession, Depends(get_session)],
    response: Response = None,  # noqa: B008 - FastAPI injects this
) -> JobAccepted:
    if mock.demo_mode():
        job = mock.job("nlp.cluster", "pending")
        return JobAccepted(
            job_id=job.id,
            status="pending",
            status_url=f"/api/v1/jobs/{job.id}",
            kind="nlp.cluster",
            message="DEMO_MODE: no work was enqueued.",
        )
    from app.services.jobs import enqueue

    return await enqueue(session, kind="nlp.cluster", project_id=project_id, params={})


@router.get("/{narrative_id}", response_model=NarrativeDetail, summary="Narrative detail")
async def get_narrative(
    narrative_id: str,
    principal: RequireRead,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> NarrativeDetail:
    if mock.demo_mode():
        return mock.to_narrative_detail(_demo_narrative(narrative_id))
    from app.repositories.narratives import get_narrative as query_narrative

    return await query_narrative(session, narrative_id)


@router.patch(
    "/{narrative_id}",
    response_model=NarrativeDetail,
    summary="Rename or curate a narrative",
    description=(
        "Sets `edited_by_user`. A subsequent `nlp.cluster` run must not overwrite any "
        "field an analyst has touched -- enforced in the task, not in the client."
    ),
)
async def update_narrative(
    narrative_id: str,
    body: NarrativeUpdate,
    principal: RequireWrite,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> NarrativeDetail:
    if mock.demo_mode():
        narrative = _demo_narrative(narrative_id)
        return mock.to_narrative_detail(narrative)
    from app.repositories.narratives import update_narrative as apply_update

    return await apply_update(session, narrative_id, body, actor=principal.name)


@router.get(
    "/{narrative_id}/timeline", response_model=NarrativeTimeline, summary="Narrative over time"
)
async def narrative_timeline(
    narrative_id: str,
    principal: RequireRead,
    session: Annotated[AsyncSession, Depends(get_session)],
    interval: Annotated[str, Query(pattern="^(1h|6h|1d|7d)$")] = "1d",
    tz: str = "UTC",
    cross_platform: bool = False,
) -> NarrativeTimeline:
    if mock.demo_mode():
        return mock.narrative_timeline(_demo_narrative(narrative_id), interval, tz, cross_platform)
    from app.repositories.narratives import narrative_timeline as query_timeline

    return await query_timeline(session, narrative_id, interval, tz, cross_platform)


@router.get(
    "/{narrative_id}/posts", response_model=PageResponse[PostOut], summary="Narrative members"
)
async def narrative_posts(
    narrative_id: str,
    principal: RequireRead,
    filters: Filters,
    page: Pagination,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> PageResponse[PostOut]:
    if mock.demo_mode():
        narrative = _demo_narrative(narrative_id)
        posts = [mock.corpus().by_post[pid] for pid in narrative.post_ids]
        posts = mock.apply_post_filters(posts, filters)
        return mock.paginate([mock.to_post(p) for p in posts], page, filters.as_response_dict())
    from app.repositories.narratives import narrative_posts as query_posts

    return await query_posts(session, narrative_id, filters, page)


@router.get(
    "/{narrative_id}/authors", response_model=PageResponse[AuthorOut], summary="Narrative authors"
)
async def narrative_authors(
    narrative_id: str,
    principal: RequireRead,
    filters: Filters,
    page: Pagination,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> PageResponse[AuthorOut]:
    if mock.demo_mode():
        narrative = _demo_narrative(narrative_id)
        authors = [mock.corpus().by_author[a] for a in narrative.author_ids]
        return mock.paginate([mock.to_author(a) for a in authors], page, filters.as_response_dict())
    from app.repositories.narratives import narrative_authors as query_authors

    return await query_authors(session, narrative_id, filters, page)


@router.get(
    "/{narrative_id}/cohorts",
    response_model=list[NarrativeCohortShare],
    summary="Top cohorts in this narrative",
)
async def narrative_cohorts(
    narrative_id: str,
    principal: RequireRead,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> list[NarrativeCohortShare]:
    if mock.demo_mode():
        return mock.narrative_cohorts(_demo_narrative(narrative_id))
    from app.repositories.narratives import narrative_cohorts as query_cohorts

    return await query_cohorts(session, narrative_id)


@router.get(
    "/{narrative_id}/score",
    response_model=NarrativeScoreExplanation,
    summary="Why this narrative scores what it scores",
    description=(
        "The explainability endpoint. Returns the fusion score decomposed into its "
        "narrative-severity, coordination and authenticity components, with the weights "
        "and formula version that produced it. A component that could not be computed "
        "is null and named in `missing`, and the remaining weights are renormalized -- "
        "never treated as a zero, which would systematically under-flag."
    ),
)
async def narrative_score(
    narrative_id: str,
    principal: RequireRead,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> NarrativeScoreExplanation:
    if mock.demo_mode():
        return mock.narrative_score(_demo_narrative(narrative_id))
    from app.repositories.narratives import narrative_score as query_score

    return await query_score(session, narrative_id)


# ---------------------------------------------------------------------------
# compass context
# ---------------------------------------------------------------------------
@router.get(
    "/{narrative_id}/compass",
    response_model=CompassContext,
    summary="Compass Context for a narrative",
    description=(
        "A RAG-generated, mandatorily-cited analyst note. When retrieval could not "
        "source the claim, `verification_status` is `insufficient_evidence` and "
        "`context` is an empty string -- an empty field is honest where an uncited "
        "paragraph is not."
    ),
)
async def narrative_compass(
    narrative_id: str,
    principal: RequireRead,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> CompassContext:
    if mock.demo_mode():
        context = mock.compass_context(_demo_narrative(narrative_id))
        if context is None:
            raise NotFound(
                "No Compass Context has been generated for this narrative yet.",
                code="compass_context_not_found",
                detail={"narrative_id": narrative_id, "hint": "POST .../compass/regenerate"},
            )
        return context
    from app.repositories.compass import latest_context

    return await latest_context(session, narrative_id)


@router.post(
    "/{narrative_id}/compass/regenerate",
    response_model=JobAccepted,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Regenerate Compass Context",
    description=(
        "Inserts a new row and marks the previous one `superseded_by`. Nothing is "
        "mutated: analysts need the audit trail of what the system said and when."
    ),
)
async def regenerate_compass(
    narrative_id: str,
    principal: RequireWrite,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> JobAccepted:
    if mock.demo_mode():
        job = mock.job("compass.generate", "pending")
        return JobAccepted(
            job_id=job.id,
            status="pending",
            status_url=f"/api/v1/jobs/{job.id}",
            kind="compass.generate",
            message="DEMO_MODE: no work was enqueued.",
        )
    from app.services.jobs import enqueue

    return await enqueue(
        session, kind="compass.generate", project_id=None, params={"narrative_id": narrative_id}
    )


@compass_router.post(
    "/{context_id}/feedback",
    response_model=CompassFeedbackResult,
    summary="Rate a Compass Context",
    description="Thumbs up/down, stored for the writeup's error analysis.",
)
async def compass_feedback(
    context_id: str,
    body: CompassFeedback,
    principal: RequireWrite,
    session: Annotated[AsyncSession, Depends(get_session)],
) -> CompassFeedbackResult:
    if mock.demo_mode():
        return CompassFeedbackResult(
            context_id=context_id,
            recorded=True,
            helpful_count=7 + (1 if body.helpful else 0),
            unhelpful_count=2 + (0 if body.helpful else 1),
        )
    from app.repositories.compass import record_feedback

    return await record_feedback(session, context_id, body, actor=principal.name)
