"""Response primitives every router shares.

These types are the frontend contract's vocabulary. Changing one changes every
page of the dashboard, which is why they live in one file with the reasoning
attached rather than being re-declared per router.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Generic, Literal, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T")


class Camel(BaseModel):
    """Base for every response model.

    ``populate_by_name`` and snake_case field names, deliberately: the UI spec's
    JSON is snake_case throughout, and a camelCase alias layer is one more place
    for the two sides to disagree about a field name.
    """

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


# ---------------------------------------------------------------------------
# AI provenance
# ---------------------------------------------------------------------------
class AiProvenance(Camel):
    """Attached to every string a model wrote.

    The UI renders its `✨ Generated by AI` pill from these fields. The frontend
    is never asked to infer whether a title came from a model or an analyst --
    that inference would be wrong exactly when it matters, on a narrative an
    analyst renamed after disagreeing with the model.
    """

    generated_by: Literal["ai", "human", "heuristic"] = Field(
        description=(
            "'ai' = written by a language model. 'heuristic' = derived from centroid "
            "keywords with no model in the loop. 'human' = written or edited by an analyst."
        )
    )
    model: str | None = Field(default=None, description="Model id that produced the string.")
    generated_at: datetime | None = None
    prompt_version: str | None = None
    edited_by_user: bool = Field(
        default=False,
        description=(
            "True once an analyst has edited the string. Reclustering must not overwrite it."
        ),
    )


class GeneratedText(Camel):
    """A string plus how it came to exist."""

    text: str | None = None
    provenance: AiProvenance


# ---------------------------------------------------------------------------
# metrics
# ---------------------------------------------------------------------------
class Metric(Camel):
    """A KPI value that carries its own definition.

    The UI spec requires a `(?)` tooltip on every KPI explaining exactly how it
    was computed. That text is the backend's job, not the frontend's: only the
    backend knows what the query actually summed, which nulls it skipped, and
    which rows the filter excluded. A frontend-authored definition is a guess
    that goes stale the first time the query changes.
    """

    value: float | int | None
    label: str
    definition: str
    unit: str | None = None
    #: Fields that were NULL for some rows in this aggregation. `NULL` means
    #: "not measured" and is never coalesced to zero, so a metric summed over a
    #: column with nulls has to say so or the number is misleading.
    nullable_fields: list[str] = Field(default_factory=list)
    #: How many rows contributed. A percentage over 12 posts and one over 12,000
    #: are different claims and the UI renders them differently.
    sample_size: int | None = None
    delta_pct: float | None = Field(
        default=None,
        description="Change against the preceding window of equal length, if computed.",
    )


class ScoreComponent(Camel):
    """One input to a fusion score, with the weight that was applied to it."""

    name: str
    value: float | None = Field(description="Normalized to [0,1]. Null means not measured.")
    weight: float
    contribution: float | None = Field(
        default=None, description="value * renormalized weight; null when value is null."
    )
    definition: str
    inputs: dict[str, Any] = Field(
        default_factory=dict, description="The raw sub-signals this component was computed from."
    )


# ---------------------------------------------------------------------------
# envelopes
# ---------------------------------------------------------------------------
class Cursor(Camel):
    next_cursor: str | None = None
    total: int | None = Field(
        default=None,
        description=(
            "Exact count when it is cheap, null when counting the full result set would "
            "cost more than the page itself. Never a guess."
        ),
    )


class PageResponse(Camel, Generic[T]):
    """The shape of every list endpoint in this API."""

    items: list[T]
    next_cursor: str | None = None
    total: int | None = None
    filters_applied: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "The filter spec that produced these rows, echoed so a surprising number is debuggable."
        ),
    )


class JobAccepted(Camel):
    """The 202 body for anything that starts work.

    One shape for every async operation, so the frontend polls one endpoint
    regardless of what it kicked off.
    """

    job_id: str
    status: Literal["pending", "running", "succeeded", "failed", "cancelled"] = "pending"
    status_url: str
    kind: str
    message: str | None = None


class ErrorDetail(Camel):
    code: str
    message: str
    detail: dict[str, Any] = Field(default_factory=dict)
    request_id: str | None = None


class ErrorResponse(Camel):
    error: ErrorDetail


class DeletedResponse(Camel):
    deleted: bool = True
    id: str
