"""Compass Context -- the fact-check engine's output.

The generation rules are enforced in ``app/compass/validate.py``, not in a
prompt, and the schema is shaped to make them visible:

* every context is a **RAG output with mandatory citation**. ``citations`` carry
  the character span in ``context`` they support, so the UI can underline the
  sourced claim rather than showing a bibliography and hoping.
* a context that fails citation validation twice is persisted with
  ``verification_status='insufficient_evidence'`` and an **empty** context.
  Persisting an uncited AI fact-check into a misinformation product is the worst
  failure this system has, and an empty field is honest where a paragraph is
  not.
* regeneration inserts a new row and marks the old one ``superseded_by``. The
  audit trail is the deliverable, not the latest answer.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import Field

from app.schemas.common import Camel

VerificationStatus = Literal[
    "unverified",
    "partially_substantiated",
    "substantiated",
    "debunked",
    "insufficient_evidence",
]


class Citation(Camel):
    id: str
    url: str
    title: str | None = None
    publisher: str | None = None
    domain: str | None = None
    retrieved_at: datetime | None = None
    snippet: str | None = Field(
        default=None, description="The retrieved passage the claim was generated over."
    )
    char_start: int | None = Field(
        default=None, description="Start of the span in `context` this citation supports."
    )
    char_end: int | None = None


class CompassContext(Camel):
    id: str
    narrative_id: str
    claim: str = Field(description="The narrative's assertion, restated neutrally.")
    context: str = Field(
        description=(
            "A hedged analyst note over retrieved sources. Empty string when "
            "verification_status is insufficient_evidence -- an empty field is honest "
            "where an uncited paragraph is not."
        )
    )
    verification_status: VerificationStatus
    risk: Literal["high", "medium", "low"]
    caution_note: str | None = Field(
        default=None,
        description="What the reader should not conclude from this context.",
    )
    citations: list[Citation] = Field(default_factory=list)
    #: Provenance. The UI renders its `✨ Generated by AI` pill from these.
    generated_by: Literal["ai"] = "ai"
    model: str
    prompt_version: str
    generated_at: datetime
    superseded_by: str | None = Field(
        default=None, description="Set when a regeneration replaced this row. Never mutated."
    )
    #: How many retrieval->generate->validate rounds it took. Surfaced because a
    #: context that needed two attempts is worth an analyst's extra scrutiny.
    attempts: int = 1
    retrieved_document_count: int = 0


class CompassFeedback(Camel):
    """Thumbs up/down, stored for the writeup's error analysis."""

    helpful: bool
    reason: str | None = Field(default=None, max_length=2000)
    reason_code: (
        Literal[
            "wrong_claim",
            "bad_sources",
            "overstated",
            "understated",
            "outdated",
            "irrelevant",
            "other",
        ]
        | None
    ) = None


class CompassFeedbackResult(Camel):
    context_id: str
    recorded: bool = True
    helpful_count: int
    unhelpful_count: int
