"""full schema

Every remaining table: the corpus, the four pillars, Compass, embeddings and the
operational tables. Three things here are hand-written on top of autogenerate,
because autogenerate cannot see them:

* ``narrative_display_id_seq``, created before ``narratives`` and dropped after
  it. The sequence backs the human-facing "ID: ####" analysts read aloud.
* The pgvector HNSW index, created **after** the table with explicit build
  parameters. It is deliberately not declared on the model: autogenerate cannot
  round-trip the operator class or `m`/`ef_construction`, and would drop and
  rebuild it on every future migration.
* A ``CHECK`` on ``ingest_runs`` asserting the reject accounting adds up. Silent
  data loss between Parquet and Postgres is the failure mode that ruins this
  project, and the database is a better place to enforce that than a comment.

Revision ID: fd81d9a3a7a6
Revises: 4557326ec7c5
Create Date: 2026-08-23 16:33:53.691705+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.config import get_api_settings

revision: str = "fd81d9a3a7a6"
down_revision: str | None = "4557326ec7c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The display_id sequence must exist before narratives references it in a
    # server_default. Alembic autogenerate does not emit sequences.
    op.execute("CREATE SEQUENCE IF NOT EXISTS narrative_display_id_seq START 1000")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "channels",
            postgresql.ARRAY(sa.String(length=16)),
            server_default=sa.text("'{in_app}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_alert_rules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index(
        "ix_alert_rules_enabled",
        "alert_rules",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_table(
        "author_groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_curated", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_author_groups_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author_groups")),
        sa.UniqueConstraint("project_id", "name", name="uq_author_groups_project_id_name"),
    )
    op.create_table(
        "clustering_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding_model", sa.String(length=256), nullable=True),
        sa.Column("post_count", sa.Integer(), nullable=True),
        sa.Column("narrative_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_clustering_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clustering_runs")),
    )
    op.create_index(
        "ix_clustering_runs_project_started",
        "clustering_runs",
        ["project_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "cohorts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("author_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("post_pct", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cohorts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohorts")),
        sa.UniqueConstraint("project_id", "name", name="uq_cohorts_project_id_name"),
    )
    op.create_index(
        "ix_cohorts_project_category", "cohorts", ["project_id", "category"], unique=False
    )
    op.create_table(
        "comparisons",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("narrative_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "platforms", postgresql.ARRAY(sa.String(length=32)), server_default="{}", nullable=False
        ),
        sa.Column("entity_type", sa.String(length=16), server_default="author", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_comparisons_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparisons")),
    )
    op.create_index("ix_comparisons_project", "comparisons", ["project_id"], unique=False)
    op.create_table(
        "domains",
        sa.Column("domain", sa.String(length=320), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_band", sa.String(length=8), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("author_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("narrative_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("whois_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hosting_country", sa.String(length=8), nullable=True),
        sa.Column("tls_cert_age_days", sa.Integer(), nullable=True),
        sa.Column("registrar", sa.String(length=256), nullable=True),
        sa.Column(
            "enrichment_status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enrichment_detail", sa.Text(), nullable=True),
        sa.Column("enrichment_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("link_velocity", sa.Float(), nullable=True),
        sa.Column("sharing_author_bot_ratio", sa.Float(), nullable=True),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scoring_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_domains_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("domain", "project_id", name=op.f("pk_domains")),
    )
    op.create_index(
        "ix_domains_enrichment_pending",
        "domains",
        ["enrichment_status"],
        unique=False,
        postgresql_where=sa.text("enrichment_status = 'pending'"),
    )
    op.create_index(
        "ix_domains_project_risk",
        "domains",
        ["project_id", sa.literal_column("risk_score DESC NULLS LAST")],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("celery_task_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_jobs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_active",
        "jobs",
        ["kind"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_index("ix_jobs_created", "jobs", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index(
        "ix_jobs_project_kind",
        "jobs",
        ["project_id", "kind", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.String(length=320), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("native_id", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_detail", sa.String(length=256), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("author_id", sa.String(length=320), nullable=False),
        sa.Column("author_handle", sa.String(length=256), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_id", sa.String(length=320), nullable=True),
        sa.Column("conversation_id", sa.String(length=320), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("replies", sa.Integer(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("urls", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("media_urls", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("hashtags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("mentions", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_posts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    op.create_index("ix_posts_author_id", "posts", ["author_id"], unique=False)
    op.create_index("ix_posts_conversation_id", "posts", ["conversation_id"], unique=False)
    op.create_index(
        "ix_posts_domains_gin", "posts", ["domains"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_posts_hashtags_gin", "posts", ["hashtags"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_posts_project_timestamp",
        "posts",
        ["project_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "ix_posts_raw_gin",
        "posts",
        ["raw"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"raw": "jsonb_path_ops"},
    )
    op.create_index("ix_posts_simhash", "posts", ["simhash"], unique=False)
    op.create_index(
        "ix_posts_source_timestamp",
        "posts",
        ["source", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "ix_posts_text_fts",
        "posts",
        [sa.literal_column("to_tsvector('english', text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "authors",
        sa.Column("author_id", sa.String(length=320), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("handle", sa.String(length=256), nullable=True),
        sa.Column("created_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("followers", sa.Integer(), nullable=True),
        sa.Column("following", sa.Integer(), nullable=True),
        sa.Column("post_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_bot_flagged", sa.Boolean(), nullable=True),
        sa.Column("bot_score", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("partisan_lean", sa.Float(), nullable=True),
        sa.Column("dominant_sentiment", sa.String(length=16), nullable=True),
        sa.Column("dominant_emotion", sa.String(length=24), nullable=True),
        sa.Column("anomalous_score", sa.Float(), nullable=True),
        sa.Column("toxicity_score", sa.Float(), nullable=True),
        sa.Column("coordination_score", sa.Float(), nullable=True),
        sa.Column("community_id", sa.String(length=64), nullable=True),
        sa.Column("community_size", sa.Integer(), nullable=True),
        sa.Column("author_group_id", sa.UUID(), nullable=True),
        sa.Column(
            "skip_reasons",
            postgresql.ARRAY(sa.String(length=64)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("scoring_version", sa.String(length=64), nullable=True),
        sa.Column("score_components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_group_id"],
            ["author_groups.id"],
            name=op.f("fk_authors_author_group_id_author_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_authors_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("author_id", name=op.f("pk_authors")),
    )
    op.create_index("ix_authors_community", "authors", ["project_id", "community_id"], unique=False)
    op.create_index(
        "ix_authors_handle_trgm",
        "authors",
        ["handle"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"handle": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_authors_project_bot",
        "authors",
        ["project_id", sa.literal_column("bot_score DESC")],
        unique=False,
        postgresql_where=sa.text("bot_score IS NOT NULL"),
    )
    op.create_index(
        "ix_authors_project_risk",
        "authors",
        ["project_id", sa.literal_column("risk_score DESC NULLS LAST")],
        unique=False,
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("records_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_loaded", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_rejected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejection_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rejects_path", sa.Text(), nullable=True),
        sa.Column("manifest_sha", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_ingest_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_ingest_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(
        "ix_ingest_runs_project_started",
        "ingest_runs",
        ["project_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "media_checks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("post_id", sa.String(length=320), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("media_type", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("verdict", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("manipulation_type", sa.String(length=48), nullable=True),
        sa.Column("frames_analyzed", sa.Integer(), nullable=True),
        sa.Column("face_detected", sa.Boolean(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("limitations", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_media_checks_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_media_checks_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_checks")),
    )
    op.create_index(
        "ix_media_checks_pending_purge",
        "media_checks",
        ["deletes_at"],
        unique=False,
        postgresql_where=sa.text("purged_at IS NULL AND storage_path IS NOT NULL"),
    )
    op.create_index(
        "ix_media_checks_submitted",
        "media_checks",
        [sa.literal_column("submitted_at DESC")],
        unique=False,
    )
    op.create_table(
        "narratives",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "display_id",
            sa.BigInteger(),
            server_default=sa.text("nextval('narrative_display_id_seq')"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "title_generated_by", sa.String(length=16), server_default="heuristic", nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_generated_by", sa.String(length=16), server_default="heuristic", nullable=False
        ),
        sa.Column("summary_model", sa.String(length=128), nullable=True),
        sa.Column("summary_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim", sa.Text(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("clustering_run_id", sa.UUID(), nullable=True),
        sa.Column("date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("author_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("engagement_total", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "platforms", postgresql.ARRAY(sa.String(length=32)), server_default="{}", nullable=False
        ),
        sa.Column("top_domains", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("top_hashtags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("coherence", sa.Float(), nullable=True),
        sa.Column("velocity", sa.Float(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("edited_by_user", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("edited_by", sa.String(length=128), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "edited_fields",
            postgresql.ARRAY(sa.String(length=32)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clustering_run_id"],
            ["clustering_runs.id"],
            name=op.f("fk_narratives_clustering_run_id_clustering_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_narratives_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_narratives")),
        sa.UniqueConstraint("display_id", name=op.f("uq_narratives_display_id")),
    )
    op.create_index(
        "ix_narratives_project_cluster",
        "narratives",
        ["project_id", "clustering_run_id", "cluster_id"],
        unique=False,
    )
    op.create_index(
        "ix_narratives_project_updated",
        "narratives",
        ["project_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_index("ix_narratives_run", "narratives", ["clustering_run_id"], unique=False)
    op.create_table(
        "post_embeddings_384",
        sa.Column("post_id", sa.String(length=320), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_embeddings_384_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_post_embeddings_384")),
        comment="L2-normalized 384-d vectors; cosine distance only.",
    )
    op.create_index("ix_post_embeddings_384_model", "post_embeddings_384", ["model"], unique=False)
    op.create_table(
        "post_scores",
        sa.Column("post_id", sa.String(length=320), nullable=False),
        sa.Column("toxicity", sa.Float(), nullable=True),
        sa.Column("is_toxic", sa.Boolean(), nullable=True),
        sa.Column("anomaly", sa.Float(), nullable=True),
        sa.Column("is_anomalous", sa.Boolean(), nullable=True),
        sa.Column("misinfo_likelihood", sa.Float(), nullable=True),
        sa.Column("stance", sa.String(length=32), nullable=True),
        sa.Column("stance_confidence", sa.Float(), nullable=True),
        sa.Column("sentiment", sa.String(length=16), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("emotion", sa.String(length=24), nullable=True),
        sa.Column("emotion_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "skip_reasons",
            postgresql.ARRAY(sa.String(length=64)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scoring_version", sa.String(length=64), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_scores_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_post_scores")),
    )
    op.create_index("ix_post_scores_emotion", "post_scores", ["emotion"], unique=False)
    op.create_index(
        "ix_post_scores_misinfo",
        "post_scores",
        [sa.literal_column("misinfo_likelihood DESC")],
        unique=False,
        postgresql_where=sa.text("misinfo_likelihood IS NOT NULL"),
    )
    op.create_index("ix_post_scores_sentiment", "post_scores", ["sentiment"], unique=False)
    op.create_index(
        "ix_post_scores_toxicity",
        "post_scores",
        [sa.literal_column("toxicity DESC")],
        unique=False,
        postgresql_where=sa.text("toxicity IS NOT NULL"),
    )
    op.create_index("ix_post_scores_version", "post_scores", ["scoring_version"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("template", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_reports_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_project_created",
        "reports",
        ["project_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("narrative_id", sa.UUID(), nullable=True),
        sa.Column("subject_type", sa.String(length=16), server_default="narrative", nullable=False),
        sa.Column("subject_id", sa.String(length=320), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_alerts_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_alerts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_alerts_rule_id_alert_rules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_project_triggered",
        "alerts",
        ["project_id", sa.literal_column("triggered_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_alerts_rule_subject",
        "alerts",
        ["rule_id", "subject_id", sa.literal_column("triggered_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_alerts_unacknowledged",
        "alerts",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("acknowledged_at IS NULL"),
    )
    op.create_table(
        "author_cohorts",
        sa.Column("author_id", sa.String(length=320), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("assigned_by", sa.String(length=16), server_default="model", nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.author_id"],
            name=op.f("fk_author_cohorts_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohorts.id"],
            name=op.f("fk_author_cohorts_cohort_id_cohorts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("author_id", "cohort_id", name=op.f("pk_author_cohorts")),
    )
    op.create_index("ix_author_cohorts_cohort", "author_cohorts", ["cohort_id"], unique=False)
    op.create_table(
        "author_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.String(length=320), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("added_by", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.author_id"],
            name=op.f("fk_author_group_members_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["author_groups.id"],
            name=op.f("fk_author_group_members_group_id_author_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "author_id", name=op.f("pk_author_group_members")),
    )
    op.create_index(
        "ix_author_group_members_author", "author_group_members", ["author_id"], unique=False
    )
    op.create_table(
        "compass_contexts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("narrative_id", sa.UUID(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), server_default="", nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("risk", sa.String(length=8), server_default="medium", nullable=False),
        sa.Column("caution_note", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("retrieved_document_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_compass_contexts_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["compass_contexts.id"],
            name=op.f("fk_compass_contexts_superseded_by_compass_contexts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compass_contexts")),
    )
    op.create_index(
        "ix_compass_contexts_current",
        "compass_contexts",
        ["narrative_id"],
        unique=False,
        postgresql_where=sa.text("superseded_by IS NULL"),
    )
    op.create_index(
        "ix_compass_contexts_narrative_time",
        "compass_contexts",
        ["narrative_id", sa.literal_column("generated_at DESC")],
        unique=False,
    )
    op.create_table(
        "narrative_posts",
        sa.Column("narrative_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.String(length=320), nullable=False),
        sa.Column("membership_score", sa.Float(), nullable=True),
        sa.Column("is_representative", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_narrative_posts_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_narrative_posts_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("narrative_id", "post_id", name=op.f("pk_narrative_posts")),
    )
    op.create_index("ix_narrative_posts_post", "narrative_posts", ["post_id"], unique=False)
    op.create_index(
        "ix_narrative_posts_representative",
        "narrative_posts",
        ["narrative_id"],
        unique=False,
        postgresql_where=sa.text("is_representative"),
    )
    op.create_table(
        "narrative_scorecards",
        sa.Column("narrative_id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("bot_like", sa.Float(), nullable=True),
        sa.Column("anomalous", sa.Float(), nullable=True),
        sa.Column("toxicity", sa.Float(), nullable=True),
        sa.Column("compass_risk", sa.String(length=8), nullable=True),
        sa.Column("negative_sentiment", sa.Float(), nullable=True),
        sa.Column("fusion_score", sa.Float(), nullable=True),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scoring_version", sa.String(length=64), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_narrative_scorecards_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("narrative_id", name=op.f("pk_narrative_scorecards")),
    )
    op.create_index(
        "ix_scorecards_fusion",
        "narrative_scorecards",
        [sa.literal_column("fusion_score DESC")],
        unique=False,
        postgresql_where=sa.text("fusion_score IS NOT NULL"),
    )
    op.create_index("ix_scorecards_priority", "narrative_scorecards", ["priority"], unique=False)
    op.create_index(
        "ix_scorecards_version", "narrative_scorecards", ["scoring_version"], unique=False
    )
    op.create_table(
        "network_edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("narrative_id", sa.UUID(), nullable=True),
        sa.Column("src_author_id", sa.String(length=320), nullable=False),
        sa.Column("dst_author_id", sa.String(length=320), nullable=False),
        sa.Column("edge_type", sa.String(length=24), nullable=False),
        sa.Column("weight", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observations", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_network_edges_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_network_edges_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_network_edges")),
    )
    op.create_index(
        "ix_network_edges_dst", "network_edges", ["project_id", "dst_author_id"], unique=False
    )
    op.create_index(
        "ix_network_edges_scope_bucket",
        "network_edges",
        ["project_id", "narrative_id", "bucket_start"],
        unique=False,
    )
    op.create_index(
        "ix_network_edges_src", "network_edges", ["project_id", "src_author_id"], unique=False
    )
    op.create_index(
        "uq_network_edges_identity",
        "network_edges",
        [
            "project_id",
            "narrative_id",
            "src_author_id",
            "dst_author_id",
            "edge_type",
            "bucket_start",
        ],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "network_layouts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("narrative_id", sa.UUID(), nullable=True),
        sa.Column("comparison_id", sa.UUID(), nullable=True),
        sa.Column("algorithm", sa.String(length=48), nullable=False),
        sa.Column("node_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("edge_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("positions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparisons.id"],
            name=op.f("fk_network_layouts_comparison_id_comparisons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_network_layouts_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_network_layouts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_network_layouts")),
    )
    op.create_index(
        "ix_network_layouts_scope",
        "network_layouts",
        ["project_id", "narrative_id", "comparison_id"],
        unique=False,
    )
    op.create_table(
        "compass_citations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("publisher", sa.String(length=256), nullable=True),
        sa.Column("domain", sa.String(length=320), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["compass_contexts.id"],
            name=op.f("fk_compass_citations_context_id_compass_contexts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compass_citations")),
    )
    op.create_index(
        "ix_compass_citations_context", "compass_citations", ["context_id"], unique=False
    )
    op.create_table(
        "compass_feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("helpful", sa.Boolean(), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("submitted_by", sa.String(length=128), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["compass_contexts.id"],
            name=op.f("fk_compass_feedback_context_id_compass_contexts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compass_feedback")),
    )
    op.create_index("ix_compass_feedback_context", "compass_feedback", ["context_id"], unique=False)
    # ### end Alembic commands ###

    _create_hnsw_index()
    _add_reject_accounting_check()


def downgrade() -> None:
    op.drop_constraint("reject_accounting", "ingest_runs", type_="check")
    op.execute(f"DROP INDEX IF EXISTS {_hnsw_index_name()}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_compass_feedback_context", table_name="compass_feedback")
    op.drop_table("compass_feedback")
    op.drop_index("ix_compass_citations_context", table_name="compass_citations")
    op.drop_table("compass_citations")
    op.drop_index("ix_network_layouts_scope", table_name="network_layouts")
    op.drop_table("network_layouts")
    op.drop_index(
        "uq_network_edges_identity", table_name="network_edges", postgresql_nulls_not_distinct=True
    )
    op.drop_index("ix_network_edges_src", table_name="network_edges")
    op.drop_index("ix_network_edges_scope_bucket", table_name="network_edges")
    op.drop_index("ix_network_edges_dst", table_name="network_edges")
    op.drop_table("network_edges")
    op.drop_index("ix_scorecards_version", table_name="narrative_scorecards")
    op.drop_index("ix_scorecards_priority", table_name="narrative_scorecards")
    op.drop_index(
        "ix_scorecards_fusion",
        table_name="narrative_scorecards",
        postgresql_where=sa.text("fusion_score IS NOT NULL"),
    )
    op.drop_table("narrative_scorecards")
    op.drop_index(
        "ix_narrative_posts_representative",
        table_name="narrative_posts",
        postgresql_where=sa.text("is_representative"),
    )
    op.drop_index("ix_narrative_posts_post", table_name="narrative_posts")
    op.drop_table("narrative_posts")
    op.drop_index("ix_compass_contexts_narrative_time", table_name="compass_contexts")
    op.drop_index(
        "ix_compass_contexts_current",
        table_name="compass_contexts",
        postgresql_where=sa.text("superseded_by IS NULL"),
    )
    op.drop_table("compass_contexts")
    op.drop_index("ix_author_group_members_author", table_name="author_group_members")
    op.drop_table("author_group_members")
    op.drop_index("ix_author_cohorts_cohort", table_name="author_cohorts")
    op.drop_table("author_cohorts")
    op.drop_index(
        "ix_alerts_unacknowledged",
        table_name="alerts",
        postgresql_where=sa.text("acknowledged_at IS NULL"),
    )
    op.drop_index("ix_alerts_rule_subject", table_name="alerts")
    op.drop_index("ix_alerts_project_triggered", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_reports_project_created", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_post_scores_version", table_name="post_scores")
    op.drop_index(
        "ix_post_scores_toxicity",
        table_name="post_scores",
        postgresql_where=sa.text("toxicity IS NOT NULL"),
    )
    op.drop_index("ix_post_scores_sentiment", table_name="post_scores")
    op.drop_index(
        "ix_post_scores_misinfo",
        table_name="post_scores",
        postgresql_where=sa.text("misinfo_likelihood IS NOT NULL"),
    )
    op.drop_index("ix_post_scores_emotion", table_name="post_scores")
    op.drop_table("post_scores")
    op.drop_index("ix_post_embeddings_384_model", table_name="post_embeddings_384")
    op.drop_table("post_embeddings_384")
    op.drop_index("ix_narratives_run", table_name="narratives")
    op.drop_index("ix_narratives_project_updated", table_name="narratives")
    op.drop_index("ix_narratives_project_cluster", table_name="narratives")
    op.drop_table("narratives")
    op.drop_index("ix_media_checks_submitted", table_name="media_checks")
    op.drop_index(
        "ix_media_checks_pending_purge",
        table_name="media_checks",
        postgresql_where=sa.text("purged_at IS NULL AND storage_path IS NOT NULL"),
    )
    op.drop_table("media_checks")
    op.drop_index("ix_ingest_runs_project_started", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index("ix_authors_project_risk", table_name="authors")
    op.drop_index(
        "ix_authors_project_bot",
        table_name="authors",
        postgresql_where=sa.text("bot_score IS NOT NULL"),
    )
    op.drop_index(
        "ix_authors_handle_trgm",
        table_name="authors",
        postgresql_using="gin",
        postgresql_ops={"handle": "gin_trgm_ops"},
    )
    op.drop_index("ix_authors_community", table_name="authors")
    op.drop_table("authors")
    op.drop_index("ix_posts_text_fts", table_name="posts", postgresql_using="gin")
    op.drop_index("ix_posts_source_timestamp", table_name="posts")
    op.drop_index("ix_posts_simhash", table_name="posts")
    op.drop_index(
        "ix_posts_raw_gin",
        table_name="posts",
        postgresql_using="gin",
        postgresql_ops={"raw": "jsonb_path_ops"},
    )
    op.drop_index("ix_posts_project_timestamp", table_name="posts")
    op.drop_index("ix_posts_hashtags_gin", table_name="posts", postgresql_using="gin")
    op.drop_index("ix_posts_domains_gin", table_name="posts", postgresql_using="gin")
    op.drop_index("ix_posts_conversation_id", table_name="posts")
    op.drop_index("ix_posts_author_id", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_jobs_project_kind", table_name="jobs")
    op.drop_index("ix_jobs_created", table_name="jobs")
    op.drop_index(
        "ix_jobs_active",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_table("jobs")
    op.drop_index("ix_domains_project_risk", table_name="domains")
    op.drop_index(
        "ix_domains_enrichment_pending",
        table_name="domains",
        postgresql_where=sa.text("enrichment_status = 'pending'"),
    )
    op.drop_table("domains")
    op.drop_index("ix_comparisons_project", table_name="comparisons")
    op.drop_table("comparisons")
    op.drop_index("ix_cohorts_project_category", table_name="cohorts")
    op.drop_table("cohorts")
    op.drop_index("ix_clustering_runs_project_started", table_name="clustering_runs")
    op.drop_table("clustering_runs")
    op.drop_table("author_groups")
    op.drop_index(
        "ix_alert_rules_enabled", table_name="alert_rules", postgresql_where=sa.text("enabled")
    )
    op.drop_table("alert_rules")
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS narrative_display_id_seq")


def _embedding_table() -> str:
    return f"post_embeddings_{get_api_settings().embedding_dim}"


def _hnsw_index_name() -> str:
    return f"hnsw_{_embedding_table()}_cosine"


def _create_hnsw_index() -> None:
    """Build the vector index after the table, not with it.

    On an empty table this is instant, which is the point: the ETL loads the
    corpus and *then* the embedding task runs, so the index is built over data
    that already exists in one pass rather than being maintained insert-by-insert
    through a bulk load. Building it first turns a ten-minute load into an hour.

    `vector_cosine_ops` throughout. Vectors are L2-normalized on write, and
    mixing L2 with cosine anywhere in this codebase produces nearest neighbours
    that are subtly wrong in a way no test on the index itself would catch.
    """
    settings = get_api_settings()
    op.execute(
        f"CREATE INDEX IF NOT EXISTS {_hnsw_index_name()} "
        f"ON {_embedding_table()} USING hnsw (embedding vector_cosine_ops) "
        f"WITH (m = {settings.hnsw_m}, ef_construction = {settings.hnsw_ef_construction})"
    )


def _add_reject_accounting_check() -> None:
    """The reject counts must add up, enforced by the database.

    `records_in = records_loaded + records_rejected` is the invariant that makes
    "zero rows silently dropped" verifiable rather than asserted. A loader bug
    that loses rows fails here, at write time, instead of surfacing three weeks
    later as a metric nobody can explain.
    """
    op.create_check_constraint(
        # The metadata naming convention expands this to
        # ck_ingest_runs_reject_accounting; passing the full name would
        # double the prefix.
        "reject_accounting",
        "ingest_runs",
        "records_in = records_loaded + records_rejected",
    )
