"""projects and api keys

The first migration. Also the place the schema asserts its hard prerequisites:
pgvector and pgcrypto are created by docker/postgres-init as superuser, and this
migration fails loudly rather than letting a later migration produce a table
whose vector column silently is not one.

Revision ID: 4557326ec7c5
Revises:
Create Date: 2026-08-20 18:17:50.665785+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4557326ec7c5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _require_extensions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key_hash", sa.String(length=512), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String(length=16)),
            server_default=sa.text("'{read}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(
        "ix_api_keys_prefix_active",
        "api_keys",
        ["prefix"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        "ix_api_keys_prefix_active",
        table_name="api_keys",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("api_keys")
    # ### end Alembic commands ###


def _require_extensions() -> None:
    """Fail with a usable message if the database was not initialised.

    CREATE EXTENSION needs superuser, so it happens once in
    docker/postgres-init/01-extensions.sql and never here. Checking for it is
    the difference between "vector extension missing, see docker/postgres-init"
    and a type error six migrations later that reads like a SQLAlchemy bug.
    """
    conn = op.get_bind()
    present = {
        row[0] for row in conn.execute(sa.text("SELECT extname FROM pg_extension")).fetchall()
    }
    missing = {"vector"} - present
    if missing:
        raise RuntimeError(
            f"required Postgres extension(s) missing: {sorted(missing)}. "
            "They are created by docker/postgres-init/01-extensions.sql on first "
            "boot of the db volume. If you are pointing at an existing database, "
            "run: CREATE EXTENSION vector; as a superuser."
        )
