"""widen id and handle columns for url-derived ids and article bylines

Found by loading the real Phase 1 corpus, which is the only way these get found.
The original widths came from the Phase 1 spec; the Parquet disagreed:

* ``posts.id`` reached 219 characters. News and GDELT derive ``native_id`` from
  the article URL, so a Guardian liveblog slug is the id. 512 leaves headroom.
* ``posts.author_handle`` reached 744. On news and GDELT rows Phase 1 stores the
  article *byline* in that column, and a multi-author paper's byline is a
  sentence. It is now unbounded TEXT: there is no defensible number to pick.

Widening a varchar in Postgres is a catalog-only change -- no table rewrite, no
lock beyond ACCESS EXCLUSIVE for the metadata update -- so this is cheap even on
a loaded table. Narrowing back in the downgrade is not: it rewrites and can fail
on data that no longer fits, which is noted there rather than discovered.

Revision ID: c7388ba2af9c
Revises: fd81d9a3a7a6
Create Date: 2026-08-23 16:49:17.709038+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 - autogenerate emits VECTOR() unqualified
import sqlalchemy as sa

from alembic import op

revision: str = "c7388ba2af9c"
down_revision: str | None = "fd81d9a3a7a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alerts",
        "subject_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "author_cohorts",
        "author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "author_group_members",
        "author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "authors",
        "author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "media_checks",
        "post_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "narrative_posts",
        "post_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "network_edges",
        "src_author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "network_edges",
        "dst_author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "post_embeddings_384",
        "post_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "post_scores",
        "post_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "native_id",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "author_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "author_handle",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # authors.handle mirrors posts.author_handle. The roll-up copies the most
    # recent handle forward, so a 744-character byline reaches this column the
    # moment the newest post for that outlet has one -- a failure that depends
    # on ingest order and therefore does not reproduce reliably.
    op.alter_column(
        "authors",
        "handle",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "posts",
        "parent_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "posts",
        "conversation_id",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Narrowing rewrites each table and FAILS on any row that no longer fits.
    # On a database that has seen the real corpus this downgrade will error on
    # posts.author_handle, and that is correct behaviour: the alternative is
    # silently truncating bylines.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "conversation_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=True,
    )
    op.alter_column(
        "posts",
        "parent_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=True,
    )
    op.alter_column(
        "authors",
        "handle",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "posts",
        "author_handle",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "posts",
        "author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "native_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.alter_column(
        "posts",
        "id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "post_scores",
        "post_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "post_embeddings_384",
        "post_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "network_edges",
        "dst_author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "network_edges",
        "src_author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_posts",
        "post_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "media_checks",
        "post_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=True,
    )
    op.alter_column(
        "authors",
        "author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "author_group_members",
        "author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "author_cohorts",
        "author_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "alerts",
        "subject_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=320),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
