"""Narratives, their scorecards, membership and the clustering runs behind them.

``is_manual`` and ``edited_by_user`` exist because the Compose/Curate page lets
an analyst rename a narrative or build one by hand, and **a reclustering run
must never overwrite a user-edited title.** The flags live here; the enforcement
lives in ``app/tasks/nlp.py``; the test that proves it lives in
``tests/test_tasks.py``. All three are required -- a convention that only exists
in a docstring is one refactor away from being gone.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Sequence,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, uuid_pk

PRIORITIES = ("high", "medium", "low")


class ClusteringRun(Base):
    """One execution of ``nlp.cluster``.

    Gives the UI its "Generated 48 days, 0 hrs ago" stamp and makes a
    reclustering auditable: which algorithm, which parameters, which embedding
    model, over how many posts.
    """

    __tablename__ = "clustering_runs"

    id: Mapped[uuid.UUID] = uuid_pk()
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    algorithm: Mapped[str] = mapped_column(String(64), nullable=False)
    params: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    embedding_model: Mapped[str | None] = mapped_column(String(256), nullable=True)
    post_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    narrative_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, server_default="pending")
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index("ix_clustering_runs_project_started", "project_id", text("started_at DESC")),
    )


class Narrative(TimestampMixin, Base):
    __tablename__ = "narratives"

    id: Mapped[uuid.UUID] = uuid_pk()
    #: The human-facing "ID: ####" the UI shows. A sequence rather than a hash
    #: because analysts read these aloud in meetings and quote them in reports.
    display_id: Mapped[int] = mapped_column(
        BigInteger,
        Sequence("narrative_display_id_seq", start=1000),
        server_default=text("nextval('narrative_display_id_seq')"),
        nullable=False,
        unique=True,
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )

    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: "ai" | "human" | "heuristic". Served verbatim to the UI, which renders
    #: its `✨ Generated by AI` pill from it rather than inferring.
    title_generated_by: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="heuristic"
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    summary_generated_by: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="heuristic"
    )
    summary_model: Mapped[str | None] = mapped_column(String(128), nullable=True)
    summary_generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    #: The specific factual assertion, extracted for Compass to fact-check.
    #: Distinct from the summary, which describes the cluster's behaviour.
    claim: Mapped[str | None] = mapped_column(Text, nullable=True)

    cluster_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    clustering_run_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("clustering_runs.id", ondelete="SET NULL"), nullable=True
    )

    date_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    date_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    post_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    author_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    engagement_total: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")

    platforms: Mapped[list[str]] = mapped_column(
        ARRAY(String(32)), nullable=False, server_default="{}"
    )
    top_domains: Mapped[list[str]] = mapped_column(ARRAY(Text), nullable=False, server_default="{}")
    top_hashtags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    coherence: Mapped[float | None] = mapped_column(Float, nullable=True)
    velocity: Mapped[float | None] = mapped_column(Float, nullable=True)

    #: Hand-built by an analyst. Reclustering ignores these entirely.
    is_manual: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    #: An analyst has edited at least one field. Reclustering may update counts
    #: and membership but must not touch the edited text.
    edited_by_user: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    edited_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    edited_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: Which specific fields were edited, so a recluster can refresh the ones an
    #: analyst never touched. Overwriting a hand-written title *and* discarding
    #: a freshly-computed summary would both be wrong.
    edited_fields: Mapped[list[str]] = mapped_column(
        ARRAY(String(32)), nullable=False, server_default="{}"
    )

    __table_args__ = (
        Index("ix_narratives_project_updated", "project_id", text("updated_at DESC")),
        Index("ix_narratives_run", "clustering_run_id"),
        Index(
            "ix_narratives_project_cluster",
            "project_id",
            "clustering_run_id",
            "cluster_id",
        ),
    )


class NarrativeScorecard(Base):
    """The six-field scorecard the UI renders everywhere.

    Separate from ``narratives`` so a rescore is an upsert into one small table
    that never rewrites narrative text, and so a scorecard can legitimately not
    exist yet without every narrative query needing to handle half-populated rows.
    """

    __tablename__ = "narrative_scorecards"

    narrative_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("narratives.id", ondelete="CASCADE"), primary_key=True
    )
    priority: Mapped[str | None] = mapped_column(String(8), nullable=True)
    bot_like: Mapped[float | None] = mapped_column(Float, nullable=True)
    anomalous: Mapped[float | None] = mapped_column(Float, nullable=True)
    toxicity: Mapped[float | None] = mapped_column(Float, nullable=True)
    compass_risk: Mapped[str | None] = mapped_column(String(8), nullable=True)
    negative_sentiment: Mapped[float | None] = mapped_column(Float, nullable=True)
    fusion_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    #: The full decomposition: every sub-score, every weight, every raw input,
    #: and the names of any components that could not be computed. This is what
    #: /narratives/{id}/score serves verbatim, and it is the reason a number in
    #: this product is explainable in one click.
    components: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    scoring_version: Mapped[str | None] = mapped_column(String(128), nullable=True)
    computed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index(
            "ix_scorecards_fusion",
            text("fusion_score DESC"),
            postgresql_where=text("fusion_score IS NOT NULL"),
        ),
        Index("ix_scorecards_priority", "priority"),
        Index("ix_scorecards_version", "scoring_version"),
    )


class NarrativePost(Base):
    """Membership, with confidence.

    ``membership_score`` is HDBSCAN's soft-cluster probability. Keeping it means
    the UI can show a narrative's core separately from its fringe, and a
    reclustering can move a marginal post without that looking like a bug.
    """

    __tablename__ = "narrative_posts"

    narrative_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("narratives.id", ondelete="CASCADE"), primary_key=True
    )
    post_id: Mapped[str] = mapped_column(
        String(512), ForeignKey("posts.id", ondelete="CASCADE"), primary_key=True
    )
    membership_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    is_representative: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    __table_args__ = (
        Index("ix_narrative_posts_post", "post_id"),
        Index(
            "ix_narrative_posts_representative",
            "narrative_id",
            postgresql_where=text("is_representative"),
        ),
    )


class Comparison(Base):
    """A saved narrative-vs-narrative comparison."""

    __tablename__ = "comparisons"

    id: Mapped[uuid.UUID] = uuid_pk()
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    #: A uuid array rather than a junction table: a comparison is an ordered,
    #: small, immutable set that is always read whole, and the join table would
    #: buy nothing but an extra query.
    narrative_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False
    )
    platforms: Mapped[list[str]] = mapped_column(
        ARRAY(String(32)), nullable=False, server_default="{}"
    )
    entity_type: Mapped[str] = mapped_column(String(16), nullable=False, server_default="author")
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, server_default=text("now()")
    )

    __table_args__ = (Index("ix_comparisons_project", "project_id"),)
